-- 0003_seed_questions.sql
--
-- GENERATED by scripts/generate-questions-seed.mjs from SEED_QUESTIONS in
-- src/lib/apply/questions.ts. Do not edit by hand: change the seed (or the
-- copy it imports from src/content/apply.ts) and run
--
--   npx tsx scripts/generate-questions-seed.mjs
--
-- The six questions of the initial form, in the order the wizard asks them.
-- `visible_when` is the rule grammar of docs/platform-contract.md section 6,
-- `extras` carries the copy the wizard needs beyond title and options (see
-- WizardExtras in questions.ts). Rows are matched by `key`, so rerunning
-- the file updates copy in place and leaves ids untouched.
--
-- The seven house rules in the src/content/bank-nif.ts header apply to
-- every string here.

insert into public.questions (
  id, key, answer_key, position, kind, title, help, options, extras, visible_when, active
) values
  (
    '5b1f0c1e-0001-4a6e-9d3b-0c1a2b3c4d01',
    'residence',
    'residence',
    1,
    'country',
    'Where is the address on your proof of address?',
    'The country on the bank statement or utility bill you will upload after payment.',
    '[]'::jsonb,
    '{
      "label": "Country",
      "placeholder": "Choose a country"
    }'::jsonb,
    null,
    true
  ),
  (
    '5b1f0c1e-0002-4a6e-9d3b-0c1a2b3c4d02',
    'who',
    'applicants',
    2,
    'choice',
    'Who is applying?',
    null,
    '[
      {
        "value": "one",
        "label": "Just me",
        "description": "One NIF, one account"
      },
      {
        "value": "two",
        "label": "Me and my partner",
        "description": "Two NIFs, or a joint account"
      },
      {
        "value": "more",
        "label": "More than two of us",
        "description": "We quote families and groups on WhatsApp"
      }
    ]'::jsonb,
    '{
      "childrenCheckbox": {
        "key": "childrenNifs",
        "label": "Also NIFs for children",
        "help": "Children''s NIFs are quoted on request after the adults'' order."
      }
    }'::jsonb,
    null,
    true
  ),
  (
    '5b1f0c1e-0003-4a6e-9d3b-0c1a2b3c4d03',
    'has-nif',
    'hasNif',
    3,
    'per-person-yes-no',
    'Do you already have a Portuguese NIF?',
    'A NIF is the nine digit Portuguese tax number. If you are not sure, you do not have one.',
    '[
      {
        "value": "yes",
        "label": "Yes, I have one"
      },
      {
        "value": "no",
        "label": "Not yet"
      }
    ]'::jsonb,
    '{
      "personLabels": [
        "You",
        "Your partner"
      ],
      "coupleTitle": "Does each of you already have a Portuguese NIF?",
      "coupleOptions": [
        {
          "value": "yes",
          "label": "Yes"
        },
        {
          "value": "no",
          "label": "Not yet"
        }
      ]
    }'::jsonb,
    '{
      "all": [
        {
          "field": "applicants",
          "op": "neq",
          "value": "more"
        }
      ]
    }'::jsonb,
    true
  ),
  (
    '5b1f0c1e-0004-4a6e-9d3b-0c1a2b3c4d04',
    'bank',
    'bank',
    4,
    'choice-by-household',
    'Do you need a Portuguese bank account?',
    'Needed for the D7 proof of funds. Opened with **Novo Banco** in 1 to 3 weeks.',
    '{
      "one": [
        {
          "value": "yes",
          "label": "Yes, open one for me",
          "description": "IBAN, debit card and online banking in 1 to 3 weeks"
        },
        {
          "value": "none",
          "label": "No account, just the NIF",
          "description": "You can add an account later"
        }
      ],
      "two": [
        {
          "value": "joint",
          "label": "A joint account for both of us",
          "description": "One account, two holders"
        },
        {
          "value": "separate",
          "label": "Two separate accounts",
          "description": "We quote separate accounts on WhatsApp"
        },
        {
          "value": "none",
          "label": "No account, just the NIF",
          "description": "You can add an account later"
        }
      ]
    }'::jsonb,
    '{}'::jsonb,
    '{
      "all": [
        {
          "field": "applicants",
          "op": "neq",
          "value": "more"
        }
      ]
    }'::jsonb,
    true
  ),
  (
    '5b1f0c1e-0005-4a6e-9d3b-0c1a2b3c4d05',
    'passport',
    'passport',
    5,
    'per-person-country',
    'Which passport will you apply with?',
    'The bank''s rules depend on nationality. We tell you now if yours is one we cannot serve.',
    '[]'::jsonb,
    '{
      "personLabels": [
        "Your passport",
        "Your partner''s passport"
      ],
      "coupleTitle": "Which passports will you apply with?",
      "placeholder": "Choose a country"
    }'::jsonb,
    '{
      "all": [
        {
          "field": "applicants",
          "op": "neq",
          "value": "more"
        },
        {
          "field": "bank",
          "op": "neq",
          "value": "separate"
        }
      ]
    }'::jsonb,
    true
  ),
  (
    '5b1f0c1e-0006-4a6e-9d3b-0c1a2b3c4d06',
    'visa',
    'visa',
    6,
    'choice',
    'Which visa are you applying for, or already hold?',
    'The bank asks for proof that a visa process is under way before it opens a file.',
    '[
      {
        "value": "d7",
        "label": "D7 · Passive income"
      },
      {
        "value": "d8",
        "label": "D8 · Digital nomad"
      },
      {
        "value": "d2",
        "label": "D2 · Entrepreneur"
      },
      {
        "value": "d9",
        "label": "D9 · Golden Visa"
      },
      {
        "value": "d1",
        "label": "D1 · Work"
      },
      {
        "value": "d3",
        "label": "D3 · Highly qualified worker"
      },
      {
        "value": "d4",
        "label": "D4 · Student"
      },
      {
        "value": "d5",
        "label": "D5 · Mobile student"
      },
      {
        "value": "d6",
        "label": "D6 · Family reunification"
      },
      {
        "value": "eu-family",
        "label": "Family member of an EU citizen"
      },
      {
        "value": "none",
        "label": "Not applying for a visa"
      }
    ]'::jsonb,
    '{
      "control": "select",
      "label": "Visa",
      "placeholder": "Choose a visa"
    }'::jsonb,
    '{
      "all": [
        {
          "field": "applicants",
          "op": "neq",
          "value": "more"
        },
        {
          "field": "bank",
          "op": "in",
          "value": [
            "yes",
            "joint"
          ]
        },
        {
          "pred": "anyNonEeaPassport"
        }
      ]
    }'::jsonb,
    true
  )
on conflict (key) do update set
  answer_key   = excluded.answer_key,
  position     = excluded.position,
  kind         = excluded.kind,
  title        = excluded.title,
  help         = excluded.help,
  options      = excluded.options,
  extras       = excluded.extras,
  visible_when = excluded.visible_when,
  active       = excluded.active;
